version: '3.9'
services:
  noria_mysql:
    image: mysql:8.0
    container_name: noria_mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      SERVICE_NAME: noria_mysql
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - noria_network

  noria_mariadb:
    image: mariadb:10
    container_name: noria_mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      SERVICE_NAME: noria_mariadb
    restart: always
    ports:
      - '3308:3306'
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - noria_network

  noria_mariadb_dev:
    image: mariadb:11.0-rc
    container_name: noria_mariadb_dev
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      SERVICE_NAME: noria_mariadb_dev
    restart: always
    ports:
      - '3309:3306'
    volumes:
      - mariadb_dev-data:/var/lib/mysql
    networks:
      - noria_network

  noria_pma_server:
    image: nginx:1.24-alpine
    container_name: noria_pma_server
    ports:
      - '8200:80'
    volumes:
      - ./pma.conf:/etc/nginx/conf.d/default.conf
      - pma_static:/var/www/html
    depends_on:
      - noria_pma
    networks:
      - noria_network

  noria_pma:
    image: phpmyadmin:5.2-fpm-alpine
    container_name: noria_pma
    links:
      - noria_mysql
      - noria_mariadb
      - noria_mariadb_dev
    environment:
      PMA_ARBITRARY: 1
    restart: always
    volumes:
      - pma_static:/var/www/html
    depends_on:
      - noria_mysql
      - noria_mariadb
      - noria_mariadb_dev
    networks:
      - noria_network

  noria_redis:
    image: redis:7.0-alpine
    container_name: noria_redis
    restart: always
    ports:
      - '6389:6379'
    volumes:
      - redis-data:/data
    networks:
      - noria_network

  noria_memcached:
    image: memcached:1.6-alpine
    container_name: noria_memcached
    restart: always
    ports:
      - '11212:11211'
    networks:
      - noria_network

  noria_mailserver:
    image: axllent/mailpit
    container_name: noria_mailserver
    restart: always
    ports:
      - '8026:8025'
      - '1026:1025'
    networks:
      - noria_network

volumes:
  mysql-data:
  mariadb-data:
  mariadb_dev-data:
  redis-data:
  pma_static:

networks:
  noria_network:
    driver: bridge
    name: noria_network
    ipam:
      config:
        - subnet: 10.88.0.0/16
          gateway: 10.88.0.1
